// src/services/driver-service.ts
import { table } from '@devvai/devv-code-backend';

const USERS_TABLE_ID = 'f4eyoj5l0wzk';

export interface NewDriverInput {
  name: string;
  phone: string;
  email?: string;
  vehicleRegistration?: string;
}

export interface DriverRecord {
  _id: string;                    // id Devv
  _uid: string;                   // créateur (Devv)
  name: string;
  email?: string;
  phone: string;
  role: 'driver';
  status: 'active' | 'inactive';
  vehicle_registration?: string | null;
  createdAt: string;
  updatedAt: string;
}

/**
 * Crée un chauffeur dans la table users
 */
export async function createDriver(input: NewDriverInput): Promise<DriverRecord> {
  try {
    const now = new Date().toISOString();

    const payload = {
      name: input.name,
      phone: input.phone,
      email: input.email || null,
      role: 'driver',
      status: 'active',
      vehicle_registration: input.vehicleRegistration || null,
      createdAt: now,
      updatedAt: now,
    };

    console.log('📝 Creating driver with payload:', payload);

    await table.addItem(USERS_TABLE_ID, payload);

    console.log('✅ Driver created in users table');

    // Return the created record (note: addItem returns void, so we return payload with estimated fields)
    return {
      ...payload,
      _id: '', // Will be generated by Devv
      _uid: '', // Will be set by Devv
    } as DriverRecord;
  } catch (err: any) {
    console.error('❌ Error creating driver:', err?.message || err);
    throw new Error(err?.message || 'Impossible de créer le chauffeur');
  }
}

/**
 * Récupérer tous les chauffeurs
 */
export async function getAllDrivers(): Promise<DriverRecord[]> {
  try {
    const res = await table.getItems(USERS_TABLE_ID, {
      query: { role: 'driver' },
      limit: 1000,
    });

    return (res.items || []) as DriverRecord[];
  } catch (err: any) {
    console.error('❌ Error fetching drivers:', err?.message || err);
    return [];
  }
}

/**
 * Mettre à jour un chauffeur
 */
export async function updateDriver(id: string, updates: Partial<NewDriverInput>): Promise<void> {
  try {
    const payload: any = {
      ...updates,
      updatedAt: new Date().toISOString(),
    };

    if (updates.vehicleRegistration !== undefined) {
      payload.vehicle_registration = updates.vehicleRegistration;
      delete payload.vehicleRegistration;
    }

    await table.updateItem(USERS_TABLE_ID, {
      _id: id,
      ...payload,
    });
    console.log('✅ Driver updated:', id);
  } catch (err: any) {
    console.error('❌ Error updating driver:', err?.message || err);
    throw new Error(err?.message || 'Impossible de mettre à jour le chauffeur');
  }
}

/**
 * Désactiver un chauffeur (soft delete)
 */
export async function deactivateDriver(id: string): Promise<void> {
  try {
    await table.updateItem(USERS_TABLE_ID, {
      _id: id,
      status: 'inactive',
      updatedAt: new Date().toISOString(),
    });
    console.log('✅ Driver deactivated:', id);
  } catch (err: any) {
    console.error('❌ Error deactivating driver:', err?.message || err);
    throw new Error(err?.message || 'Impossible de désactiver le chauffeur');
  }
}
