import { table } from '@devvai/devv-code-backend';
import type { User, CreateUserData } from '../types';

// Table ID from table_list
const USERS_TABLE_ID = 'f4eyoj5l0wzk';

class UserService {
  /**
   * Get current user ID from localStorage
   */
  private getCurrentUserId(): string {
    try {
      const authStorage = localStorage.getItem('auth-storage');
      if (!authStorage) {
        throw new Error('User not authenticated');
      }
      
      const parsed = JSON.parse(authStorage);
      const uid = parsed?.state?.user?.uid;
      
      if (!uid) {
        throw new Error('User ID not found');
      }
      
      return uid;
    } catch (error) {
      throw new Error('Failed to get current user ID');
    }
  }

  /**
   * Create a new user
   */
  async createUser(data: CreateUserData): Promise<User> {
    try {
      const timestamp = new Date().toISOString();
      const currentUserId = this.getCurrentUserId();
      
      const userData = {
        _uid: currentUserId, // Required field
        email: data.email,
        phone: data.phone,
        firstName: data.firstName,
        lastName: data.lastName,
        role: data.role,
        status: data.status,
        companyName: data.companyName || '',
        address: data.address || '',
        city: data.city || '',
        country: data.country || 'Sénégal',
        createdBy: currentUserId,
        createdAt: timestamp,
        lastLogin: '',
        parentId: '',
      };

      // addItem returns void, so we construct the response
      await table.addItem(USERS_TABLE_ID, userData);
      
      // Return the user data with system fields
      return {
        ...userData,
        _id: '', // Will be generated by the system
        _tid: USERS_TABLE_ID,
      } as User;
    } catch (error: any) {
      console.error('Failed to create user:', error);
      throw new Error(error.message || 'Failed to create user');
    }
  }

  /**
   * List all users
   */
  async listUsers(): Promise<User[]> {
    try {
      const response = await table.getItems(USERS_TABLE_ID, {
        limit: 100,
      });

      return (response.items || []) as User[];
    } catch (error: any) {
      console.error('Failed to list users:', error);
      throw new Error(error.message || 'Failed to list users');
    }
  }

  /**
   * Get users by role
   */
  async getUsersByRole(role: string): Promise<User[]> {
    try {
      const response = await table.getItems(USERS_TABLE_ID, {
        query: {
          role: role,
        },
        limit: 100,
      });

      return (response.items || []) as User[];
    } catch (error: any) {
      console.error('Failed to get users by role:', error);
      throw new Error(error.message || 'Failed to get users by role');
    }
  }

  /**
   * Update user
   */
  async updateUser(userId: string, userUid: string, updates: Partial<CreateUserData>): Promise<void> {
    try {
      const updateData = {
        _uid: userUid, // Required primary key
        _id: userId,   // Required primary key
        ...updates,
      };

      // updateItem returns void
      await table.updateItem(USERS_TABLE_ID, updateData);
    } catch (error: any) {
      console.error('Failed to update user:', error);
      throw new Error(error.message || 'Failed to update user');
    }
  }

  /**
   * Delete user
   */
  async deleteUser(userId: string, userUid: string): Promise<void> {
    try {
      await table.deleteItem(USERS_TABLE_ID, {
        _uid: userUid,
        _id: userId,
      });
    } catch (error: any) {
      console.error('Failed to delete user:', error);
      throw new Error(error.message || 'Failed to delete user');
    }
  }
}

export const userService = new UserService();
